
#ToolKit common config
[playerEvent]
	#Send messages to users on join?
	message_on_join = true
	#if messageOnJoin is true this message will be send to the player on joining world
	message = "ยง5Hello from ToolKit, this message can be change or disabled in config."

